### ISSUE TITLE
Not working when "sh_word_split" enabled

### ISSUE THREAD

**Issue by aoyama-val** [soheilpro/zsh-vi-search#2]
Adding `setopt localoptions no_sh_word_split` in every function fixed the problem for me:
https://github.com/aoyama-val/zsh-vi-search/commit/b2b0936eaa9381e8acd9e59030a4d6346626e3e5

Thank you for the neat plugin! This is exactly what  I was looking for.

**Comment by soheilpro** [comment]
I didn't know about this option.

Thanks for the fix and the kind words.
